CREATE DATABASE PANDA_BANK;
USE PANDA_BANK;

SHOW TABLES;

CREATE TABLE CUSTOMER (
	
	ID_CUSTOMER				INT(10) AUTO_INCREMENT,
	CPF_CNPJ 				VARCHAR(15) NOT NULL UNIQUE,
	NAME_CUSTOMER			VARCHAR(30) NOT NULL,
    SURNAME_CUSTOMER		VARCHAR(45) NOT NULL,
	EMAIL					VARCHAR(255) NOT NULL UNIQUE,
	PASSWORD_CUSTOMER		VARCHAR(255) NOT NULL,
	DT_BORN	    			DATE NOT NULL,
	DT_REGISTER				DATE NOT NULL,
	ADDRESS					VARCHAR(255) NOT NULL,
	PHONE					VARCHAR(15) NOT NULL,	

	CONSTRAINT pk_id_customer PRIMARY KEY (ID_CUSTOMER)	
);



CREATE TABLE ACCOUNT_PANDA (
	
	ID_ACCOUNT		INT(8) AUTO_INCREMENT,
	ID_CUSTOMER		INT(10),
    AGENCY			VARCHAR(4) NOT NULL,
	ACCOUNT_TYPE	VARCHAR(10) NOT NULL,
	BALANCE		    DECIMAL(10, 2) NOT NULL,
	
	
	CONSTRAINT check_tp_account CHECK (ACCOUNT_TYPE IN ('CURRENT', 'SAVINGS')),
	CONSTRAINT fk_id_customer FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER(ID_CUSTOMER)
	ON DELETE CASCADE,
	
	CONSTRAINT pk_id_account PRIMARY KEY (ID_ACCOUNT)
);


CREATE TABLE PIX (

ID_PIX 			INT(10) AUTO_INCREMENT,
ID_CUSTOMER 	INT(10),
ID_ACCOUNT 		INT(8),
KEY_VALUE 		VARCHAR(77),
KEY_TYPE 		VARCHAR (9),

		CONSTRAINT check_tp_key CHECK (KEY_TYPE IN ('CELLPHONE_NUMBER', 'EMAIL', 'CPF','CNPJ','RANDOM')),
		CONSTRAINT fk_id_customer_pix FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER(ID_CUSTOMER)
			ON DELETE CASCADE,
		CONSTRAINT fk_id_account_pix FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNT_PANDA (ID_ACCOUNT)
			ON DELETE CASCADE,
    
		CONSTRAINT pk_id_pix PRIMARY KEY (ID_PIX)    
);


CREATE TABLE TRANSACTION_HISTORY (

ID_TRANSACTION			INT(10),
ID_CUSTOMER_SENDER 		INT(10),
ID_CUSTOMER_RECIPIENT 	INT(10),
ID_PIX_RECIPIENT 		INT(10) AUTO_INCREMENT,
ID_ACCOUNT_SENDER 		INT(8),
ID_ACCOUNT_RECIPIENT 	INT(8),
DT_TRANSACTION			DATE NOT NULL,
    
	
    
	CONSTRAINT fk_id_customer_sender FOREIGN KEY (ID_CUSTOMER_SENDER) REFERENCES CUSTOMER(ID_CUSTOMER)
		ON DELETE CASCADE,
	CONSTRAINT fk_id_customer_recipient FOREIGN KEY (ID_CUSTOMER_RECIPIENT) REFERENCES CUSTOMER(ID_CUSTOMER)
		ON DELETE CASCADE,
	CONSTRAINT fk_id_account_sender FOREIGN KEY (ID_ACCOUNT_SENDER) REFERENCES ACCOUNT_PANDA (ID_ACCOUNT)
		ON DELETE CASCADE,
    CONSTRAINT fk_id_account_recipient FOREIGN KEY (ID_ACCOUNT_RECIPIENT) REFERENCES ACCOUNT_PANDA (ID_ACCOUNT)
		ON DELETE CASCADE,
    CONSTRAINT fk_id_pix_recipient FOREIGN KEY (ID_PIX_RECIPIENT) REFERENCES PIX (ID_PIX)
		ON DELETE CASCADE,
        
        CONSTRAINT pk_id_transaction_history PRIMARY KEY (ID_TRANSACTION) 
    
);

 DROP TABLE ACCOUNT_PANDA;
 DROP TABLE CUSTOMER;
 DROP TABLE PIX;
 DROP TABLE TRANSACTION_HISTORY;

